#!/bin/sh

PATH=$PATH:$JBOSS_HOME/bin

echo "Configuring Keycloak for DR-ONE"

kc_get_client() {
    kcadm.sh get clients -r $1 -q clientId=$2 --fields id,clientId |\
        grep '"id" :' | \
        sed -e 's/.*"id" : "\(.*\)".*/\1/'
}

KC_URI="http://auth:8080"
USER=$KEYCLOAK_USER
PASSWD=$KEYCLOAK_PASSWORD
# use hardcoded secret for now
ADMIN_CLI_SECRET=${KEYCLOAK_ADMIN_CLI_SECRET:-"b37deffe-83c5-11ea-b39f-37118301889d"}

# create an admin user
#add-user-keycloak.sh -u $USER -p $PASSWORD

# log in as admin
echo "Logging in to $KC_URI/auth..."
kcadm.sh config credentials --server $KC_URI/auth --realm master \
         --user $USER --password $PASSWD

# get admin-cli client ID
ADMIN_CLIENT=admin-cli
ADMIN_CLI_ID=$(kc_get_client master $ADMIN_CLIENT)

# set admin-cli to restricted and associate the secret
echo "Configuring $ADMIN_CLIENT with confidential access type and a secret..."
kcadm.sh update clients/$ADMIN_CLI_ID \
         -s publicClient=false \
         -s clientAuthenticatorType=client-secret \
         -s secret=$ADMIN_CLI_SECRET

# re-login with the new secret
echo "Logging in to $KC_URI/auth using the secret..."
kcadm.sh config credentials --server $KC_URI/auth --realm master \
         --user $USER --password $PASSWD --secret $ADMIN_CLI_SECRET

# update tokens lifespan !!!DANGEROUS!!!
echo "Updating SSO session and max lifespan for master to 999 days"
kcadm.sh update realms/master -s ssoSessionIdleTimeout=86313600 -s ssoSessionMaxLifespan=86313600

echo "Enabling service account for $ADMIN_CLIENT..."
kcadm.sh update clients/$ADMIN_CLI_ID -s serviceAccountsEnabled=true

echo "Setting access token lifespan for $ADMIN_CLIENT to 999 days..."
kcadm.sh update clients/$ADMIN_CLI_ID -s 'attributes."access.token.lifespan"=86313600'

echo "Adding admin service role to $ADMIN_CLIENT..."
kcadm.sh add-roles -r master --rolename admin --uusername service-account-${ADMIN_CLIENT}

# load DR-ONE realm from a file
echo "Importing DR ONE realm..."
kcadm.sh create realms -f /tmp/drone-realm-export.json

