version: '3'
services:
  db:
    image: mongo
  auth:
    build:
      context: ./auth
    ports: [ '8443:8443' ]
    environment:
      KEYCLOAK_ADMIN_CLI_SECRET: ${KEYCLOAK_ADMIN_CLI_SECRET:-b37deffe-83c5-11ea-b39f-37118301889d}
      KEYCLOAK_USER: ${KEYCLOAK_USER:-admin}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD:-admin}
      KEYCLOAK_HOSTNAME: 'auth'
  dr-one:
    image: designroom/dr-one:${DR_VERSION:-latest}
    ports: [ '10101:10101', '10102:10102' ]
    command: [node, app.js, --dr_db_url=mongodb://db:27017/dr]
    environment:
      DR_HOST: ${DR_HOST:-localhost}
      DR_AUTH: ${DR_AUTH:-none}
      KC_ADMIN_SECRET: ${KEYCLOAK_ADMIN_CLI_SECRET:-b37deffe-83c5-11ea-b39f-37118301889d}
    volumes:
      - ./keycloak.json:/dr-one/OnPrem_Design_Room/config/keycloak.json
    depends_on: [ 'db' ]
